/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright Red Hat
 */

#ifndef RELEASE_VERSIONS_H
#define RELEASE_VERSIONS_H

enum {
	VDO_OXYGEN_RELEASE_VERSION_NUMBER = 109583,
	VDO_FLUORINE_RELEASE_VERSION_NUMBER = 115838,
	VDO_NEON_RELEASE_VERSION_NUMBER = 120965,
	VDO_SODIUM_RELEASE_VERSION_NUMBER = 127441,
	VDO_MAGNESIUM_RELEASE_VERSION_NUMBER = 131337,
	VDO_ALUMINUM_RELEASE_VERSION_NUMBER = 133524,
	VDO_HEAD_RELEASE_VERSION_NUMBER = 0,
	VDO_CURRENT_RELEASE_VERSION_NUMBER = VDO_HEAD_RELEASE_VERSION_NUMBER,
};

#endif /* not RELEASE_VERSIONS_H */
